### ISSUE TITLE
proposal: make the build.zig.ini file a strict subset of TOML

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14289]
Extracted from #14265.

Currently the build.zig.ini file is not valid TOML. Example:

```
[package]
name=libffmpeg
version=5.1.2

[dependency]
name=libz
url=https://github.com/andrewrk/libz/archive/f0e53cc2391741034b144a2c2076ed8a9937b29b.tar.gz
hash=c9b30cffc40999d2c078ff350cbcee642970a224fe123c756d0892f876cf1aae

[dependency]
name=libmp3lame
url=https://github.com/andrewrk/libmp3lame/archive/497568e670bfeb14ab6ef47fb6459a2251358e43.tar.gz
hash=9ba4f49895b174a3f918d489238acbc146bd393575062b2e3be33488b688e36f
```

To make it valid TOML:

```toml
[package]
name="libffmpeg"
version="5.1.2"

[[dependency]]
name="libz"
url="https://github.com/andrewrk/libz/archive/f0e53cc2391741034b144a2c2076ed8a9937b29b.tar.gz"
hash="c9b30cffc40999d2c078ff350cbcee642970a224fe123c756d0892f876cf1aae"

[[dependency]]
name="libmp3lame"
url="https://github.com/andrewrk/libmp3lame/archive/497568e670bfeb14ab6ef47fb6459a2251358e43.tar.gz"
hash="9ba4f49895b174a3f918d489238acbc146bd393575062b2e3be33488b688e36f"
```

It also should be renamed with the `.toml` extension, and furthermore, `[package]` should be renamed to `[project]` to match the correct terminology.

Let's have a short list of accepted TOML features and only use those.

See competing proposal:
 * #14290
