### ISSUE TITLE
build.zig dependencies: support url mirrors

### ISSUE THREAD

**Issue by andrewrk** [ziglang/zig#14291]
If #14289 is accepted:

```toml
[[dependency]]
name="libz"
url=["https://github.com/andrewrk/libz/archive/f0e53cc2391741034b144a2c2076ed8a9937b29b.tar.gz", "https://andrewkelley.me/temp/backup (2).tar.gz"]
hash="sha256=c9b30cffc40999d2c078ff350cbcee642970a224fe123c756d0892f876cf1aae"
```

If #14290 is accepted:

```zig
.{
    .name = "libffmpeg",
    .version = "5.1.2",
    .dependencies = .{
        .libz = .{
            .url = .{
                "https://github.com/andrewrk/libz/archive/f0e53cc2391741034b144a2c2076ed8a9937b29b.tar.gz",
                "https://andrewkelley.me/temp/backup (2).tar.gz",
            },
            .hash = "sha256=c9b30cffc40999d2c078ff350cbcee642970a224fe123c756d0892f876cf1aae",
        },
    },
}
```

Note that the hash is the same regardless of which mirror URL is used.

URL mirrors are tried in succession; if one mirror fails to deliver a directory of files with a matching hash, then the next URL is tried, and so on until all the mirrors have been tried.
