### ISSUE TITLE
zig and case insensitive (C) header problem

### ISSUE THREAD

**Issue by codehz** [ziglang/zig#6486]
We know that file names under Windows are usually case-insensitive, so there are many legacy codes that rely on this assumption.
This brings a lot of trouble to cross compilation. Fortunately, clang can handle it, but it requires a lot of manual configuration (vfsoverlay with `case-sensitive: false`).
I hope that zig can simplify this configuration, or in other words, add an header case-insensitive options under certain circumstances.

-----

the clang's vfsoverlay template
```yaml
version: 0
case-sensitive: false
roots:
  - name: (for each zig's windows header folder)
    type: directory
    contents:
      - name: (for each files)
        type: file
        external-contents: (real path to this file)
```

This situation is so common(compile windows app in linux), so I think it is more appropriate to provide this function directly by the build system
