### ISSUE TITLE
scrolling in documentation

### ISSUE THREAD

**Issue by dullbananas** [ziglang/zig#9263]
scrollong does not work on this page: https://ziglang.org/documentation/master/std/#std

**Comment by SpexGuy** [comment]
Works fine for me, what browser are you using?

**Comment by dullbananas** [comment]
iOS safari 14.6

**Comment by dbandstra** [comment]
I can replicate this on my computer in Firefox by making the browser window narrow. The problem seems to stem from `overflow-y: hidden` set on `.flex-main`.

**Comment by haze** [comment]
Also happens in iOS 15 safari

**Comment by mrakh** [comment]
A workaround is to rotate your phone to landscape mode, that seems to make the scrolling work.

**Comment by danyildiabin** [comment]
I think that's an issue for [this repo](https://github.com/ziglang/www.ziglang.org).

**Comment by TobBrandt** [comment]
The reason for this is that the flex direction of the main container switches from row to column if the width of the screen is 750px or less, but it still has overflow-y: hidden.

To fix it, change this rule:
```css
@media only screen and (max-width: 750px) {
        [...]
        .flex-main {
          flex-direction: column;
          display: block;
        }
        [...]
}
```

to

```css
@media only screen and (max-width: 750px) {
        [...]
        .flex-main {
          flex-direction: column;
          display: block;
          overflow-y: auto;
        }
        [...]
}
```

I would create a pull request, but I have no idea where this comes from.
